# -*- coding: utf-8 -*-
import os.path

# Form implementation generated from reading ui file 'UiDesign1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5 import QtCore
from PyQt5.QtGui import *
import sys


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(515, 488)
        self.browseButton = QtWidgets.QPushButton(Dialog)
        self.browseButton.setGeometry(QtCore.QRect(80, 260, 121, 71))
        self.browseButton.setObjectName("browseButton")
        self.TxtLabel1 = QtWidgets.QLabel(Dialog)
        self.TxtLabel1.setGeometry(QtCore.QRect(150, 20, 201, 201))
        self.TxtLabel1.setText("")
        self.TxtLabel1.setObjectName("TxtLabel1")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.browseButton.clicked.connect(self.loadImage)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.browseButton.setText(_translate("Dialog", "Browse"))
    def loadImage(self):
        filename, _ =QtWidgets.QFileDialog.getOpenFileName(None,"Select Image","","Image Files(*.jpeg *.png *.jpg)")
        if filename:
            print(filename)
            self.file=filename
            pixmap=QtGui.QPixmap(filename)
            pixmap=pixmap.scaled(self.TxtLabel1.width(),self.TxtLabel1.height(),QtCore.Qt.KeepAspectRatio)
            self.TxtLabel1.setPixmap(pixmap)
            self.TxtLabel1.setAlignment(QtCore.Qt.AlignLeft)
            head,tail=os.path.split(filename)
            print(tail)
            self.TxtLabel1.setText(tail)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
